name: Сборка и тестирование

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка зависимостей
        run: |
          # Команды для установки необходимых зависимостей
          # Например, для языка C++ с использованием g++
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Сборка приложения
        run: |
          # Команды для компиляции приложения
          # Например, для языка C++ с использованием g++
          g++ -o app app.cpp

      - name: Запуск теста
        run: |
          # Команда для запуска теста
          # Предполагается, что файл test.sh находится в каталоге "tests"
          bash tests/test.sh
