name: Workflow

on: workflow_dispatch
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: App
        run: |
          g++ -o app app.cpp

      - name: Run Date Test
        run: |
          chmod +x ./test/date-test.sh
          ./test/date-test.sh
        shell: bash
